<?php
session_start();
//session_destroy();
// Check if the totalAmount session variable exists
if(isset($_SESSION['totalAmount'])){
    $totalAmount = $_SESSION['totalAmount'];
} else {
    // Handle the case where the totalAmount session variable is not set
    echo "Error: Total amount not found.";
    exit;
}

$apiKey = "rzp_test_IJkqmrF2D1l6DC";
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<form action="" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $apiKey; ?>"
        data-amount="<?php echo (int)$totalAmount*100; ?>"
        data-currency="INR"
        data-id="<?php echo 'OID'.rand(10,100).'END';?>"
        data-buttontext="Pay with Razorpay"
        data-name="Food Order Website"
        data-description="To Divya Vartak"
        data-image=""
        data-prefill.name=""
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
</form>





















<!-- <?php
$apiKey="rzp_test_IJkqmrF2D1l6DC";
$totalAmount = $gt * 100;

?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount=<?php echo $totalAmount; ?>// Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Food Order Website"
    data-description="To Divya Vartak"
    data-image=""
    data-prefill.name=""
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
<style>
    .razorpay-payment-button{display: none;}
</style>

<script type="text/javascript">
$(document).ready(function(){
    $('.razorpay-payment-button').click();
});
   </script> -->